CREATE TABLE USER (
    ID LONG PRIMARY KEY,
    USER_NM VARCHAR(255) NOT NULL
);

CREATE TABLE LECTURE (
    ID LONG PRIMARY KEY,
    LECTURE_NM VARCHAR(255) NOT NULL,
    TEACHER_NM VARCHAR(255) NOT NULL,
    MAX_PERSONNEL INTEGER DEFAULT 30
);

CREATE TABLE LECTURE_SCHEDULE (
    ID LONG PRIMARY KEY,
    LECTURE_ID LONG NOT NULL,
    LECTURE_DATE TIMESTAMP NOT NULL,
    MAX_PERSONNEL INTEGER DEFAULT 30,
    CURRENT_PERSONNEL INTEGER DEFAULT 0
);

CREATE TABLE LECTURE_HISTORY (
    ID LONG PRIMARY KEY,
    LECTURE_ID LONG NOT NULL,
    USER_ID LONG NOT NULL,
    REGISTER_DATE TIMESTAMP NOT NULL
);