CREATE TABLE LECTURE (
    ID LONG PRIMARY KEY,
    LECTURE_NM VARCHAR(255) NOT NULL,
    APPLICATION_DATE TIMESTAMP NOT NULL,
    LECTURE_CAPACITY INTEGER NOT NULL
);

CREATE TABLE USER (
    ID LONG PRIMARY KEY,
    USER_NM VARCHAR(255) NOT NULL
);

CREATE TABLE LECTURE_HISTORY (
    ID LONG PRIMARY KEY,
    LECTURE_ID LONG NOT NULL,
    USER_ID LONG NOT NULL,
    APPLICATION_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (LECTURE_ID) REFERENCES LECTURE(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);