server:
  port: 8080 # ???? ??

spring:
  datasource:
    url: jdbc:h2:mem:lecture;NON_KEYWORDS=USER # h2 db in-memory ???? ?? + user ?? ??? ????? ??
    driverClassName: org.h2.Driver
    username: lecture
    password: lecture

  # SQL ???? ?? ??? ???? ??
  # always > ?????? ?? ??? SQL ???? ?? ??
  # schema.sql ? data.sql ??? ???? ?????? ???? ?? ???? ??
  sql:
    init:
      mode: always

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: update # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true  # ?? ?? ?? (??)
        show_sql: true  # ?? ?? ??