Spring:
  application:
    name: ticketing # projectName
  datasource:
    driver-class-name: org.h2.Driver
    # url: 'jdbc:h2:mem:test'  # In-Memory Mode
    # url: 'jdbc:h2:~/test'  # Embedded Mode
    #DB_CLOSE_DELAY=-1? ?????? ??? ??? ??? ???? ????? ??,
    #DB_CLOSE_ON_EXIT=FALSE? ?????? ?? ? ??????? ?? ??? ??
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # ??? ID ??? ??? ???? ??? ?????.
        # Hibernate 5??? ??? ID ??? ??? ??????, ? ??? ?? ?? ???? ? ??
        use_new_id_generator_mappings: true
        # ??? SQL? ??? ???? ??? ?????.
        # SQL ??? ??? ???? ??? ? ??? ? ? ????
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        # ??? SQL? ?? ?? ????? ??? ?????.
        # true? ???? ???? SQL? ?? ?? ???? ??
        format_sql: true
        # ??? SQL? ??? ???? ??? ?????.
        # true? ???? Hibernate? ??? SQL ??? ??? ??
        show_sql: true
